{% set name = "lxqt-build-tools" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lxqt/lxqt-build-tools/releases/download/{{ version }}/lxqt-build-tools-{{ version }}.tar.xz
  sha256: 9782878d6c0cc896d4a54fce5cc322561cdf1df270b8f941b2088a434b535e4d

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
  host:
    - qt >=5.7.1

test:
  commands:
    - test -f "$PREFIX/share/cmake/lxqt-build-tools/modules/LXQtCompilerSettings.cmake"

about:
  home: https://github.com/lxqt/lxqt-build-tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: BSD-3-Clause
  summary: Various packaging tools and scripts for LXQt applications
  doc_url: http://lxqt.org
  dev_url: https://github.com/lxqt/lxqt-build-tools

extra:
  recipe-maintainers:
    - scopatz
